[package]
name = "nb"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }

[dev-dependencies]
serial_test = "3.2.0"
tempfile = "3.24.0"
